drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text not null,
    url text not null,
    rating numeric default 1,
    description text
);

insert into bookmarks (title, url, description, rating)
values
    ('google', 'www.google.com', 'search', 5),
    ('bloc', 'www.bloc.io', 'learn', 5),
    ('github', 'www.github.com', 'git storage', 5),
    ('Duck Duck Go', 'www.duckduckgo.com', 'search', 4),
    ('thinkful', 'www.thinkful.com', 'learn', 5),
    ('Free Code Camp', 'www.freecodecamp.org', 'learn', 5),
    ('MDN web docs', 'https://developer.mozilla.org/en-US/', 'resource', 5),
    ('Stack Overflow', 'stackoverflow.com', 'resource', 3),
    ('W3 Schools', 'https://www.w3schools.com/default.asp', 'resource', 3),
    ('Codecademy', 'codecademy.com', 'learn', 4);